### ISSUE TITLE
bug: latency metric stuck

### ISSUE THREAD

**Issue by keremcankabadayi** [Trendyol/go-dcp-elasticsearch#44]
go-dcp version: v1.1.9
golang: 1.20

We use the exposed metric "cbgo_elasticsearch_connector_bulk_request_process_latency_ms_current" to measure the delay.Sometimes, one of the pods gets stuck. It's resolved when you restart the pod.

![image](https://github.com/Trendyol/go-dcp-elasticsearch/assets/23381187/6672ee4a-f053-423c-895b-ac04188b20de)

**Comment by nihatalim** [comment]
Is this issue has been solved?
