### ISSUE TITLE
bug :wrong flush message condition

### ISSUE THREAD

**Issue by uatmaca** [Trendyol/go-dcp-elasticsearch#57]
Batch flushMessage byte limit is checked incorrectly. `len(b.batch) >= b.batchByteSizeLimit` is calculating size of batch list length.

file : bulk.go

```
if b.batchSize >= b.batchSizeLimit || len(b.batch) >= b.batchByteSizeLimit {
	b.flushMessages()
}
```

**Comment by mhmtszr** [comment]
Nice catch, instead of len(b.batch) we should use b.batchByteSize
